#!/bin/bash

# SCRIPT NAME:  err_exit
#
# ABSTRACT:  This script is to be used when a fatal error or condition
# has been reached and you want to terminate the job.
#
# USAGE:  To use this script one must export the following variables to the
# script: jobid, SENDECF, pgm, pgmout, DATA. One can provide
# a message for the logfile by passing it to the script as an argument.

err=${err:-""}             # Return code from program
pgm=${pgm:-""}             # Program name
pgmout=${pgmout:-""}       # Program output file
jobid=${jobid:-"UNKNOWN"}  # Job ID
DATA=${DATA:-""}           # Working directory
SENDECF=${SENDECF:-"NO"}   # Send message to ecflow
ECF_NAME=${ECF_NAME:-""}   # Name of the ECF Job
ECF_HOST=${ECF_HOST:-""}   # ecflow hostname
ECF_JOBOUT=${ECF_JOBOUT:-""} # ecflow job output file
JOBID=${JOBID:-$PBS_JOBID}   # Scheduler Job ID e.g. $PBS_JOBID, $SLURM_ID, etc

if [[ -z "${KILLJOB:-}" ]]; then
    if [[ -n "${PBS_JOBID:-}" ]]; then
        KILLJOB="qdel"
    elif [[ -n "${SLURM_JOB_ID:-}" ]]; then
        KILLJOB="scancel"
    elif [[ -n "${LSB_JOBID:-}" ]]; then
        KILLJOB="bkill"
    else
        # Check if qdel, scancel, or bkill commands are available in the PATH
        if command -v qdel &> /dev/null; then
            KILLJOB="qdel"
        elif command -v scancel &> /dev/null; then
            KILLJOB="scancel"
        elif command -v bkill &> /dev/null; then
            KILLJOB="bkill"
        else
            echo "WARNING: Could not determine job scheduler and KILLJOB variable is not set."
            echo "         Continuing assuming that ecflow will be used to kill the job."
            KILLJOB=""
        fi
    fi
fi

msg1=${*:-Job ${jobid} failed}
if [[ -n "${pgm}" ]]; then
    msg1+=", ERROR IN ${pgm}"
fi
if [[ -n "${err}" ]]; then
    msg1+=" RETURN CODE ${err}"
fi

msg2="
-------------------------------------------------------------
-- FATAL ERROR: ${msg1}
-- ABNORMAL EXIT at $(date) on ${HOSTNAME}
-------------------------------------------------------------
"

>&2 echo "${msg2}"

# list loaded modules
module list
>&2 echo ""

>&2 echo "${msg1}"

# list files in temporary working directory
if [[ -n "${DATA}" ]]; then
    >&2 echo "${DATA}"
    >&2 ls -ltr "${DATA}"
else
    >&2 echo "WARNING: DATA variable not defined"
fi

# save standard output
if [[ -n "${pgmout}" ]]; then
    if [[ -s errfile ]]; then
        echo "----- contents of errfile -----" >> "${pgmout}"
        cat errfile >> "${pgmout}"
    fi
    >&2 cat "${pgmout}"
elif [[ -s errfile ]]; then
    >&2 cat errfile
fi

# Write to ecflow log:
if [[ "${SENDECF}" == "YES" ]]; then
    timeout 30 ecflow_client --msg "${ECF_NAME}: ${msg1}"
    if [[ -z "${ECF_JOBOUT}" || "${ECF_HOST}" == "" ]]; then
        echo "FATAL ERROR Unable to write to ecflow server as either ECF_HOST or ECF_JOBOUT are undefined!!"
    else
        timeout 30 ssh "${ECF_HOST}" "echo \"${msg2}\" >> ${ECF_JOBOUT}"
    fi
fi

# KILL THE JOB VIA ECFLOW:
if [[ "${SENDECF}" == "YES" ]]; then
    if [[ -z "${ECF_NAME}" ]]; then
        echo "FATAL ERROR Unable to kill ecflow job as ECF_NAME variable is not set!!"
    else
        echo "Killing the job via ecflow kill"
        ecflow_client --kill="${ECF_NAME}"
    fi
# KILL THE JOB VIA JOB SCHEDULER COMMAND:
elif [[ -n "${KILLJOB}" && -n "${JOBID}" ]]; then
    echo "Killing the job via ${KILLJOB}"
    ${KILLJOB} ${JOBID}
else
    echo "Could not find a scheduler command or job ID to kill the current job"
    echo "KILLJOB = ${KILLJOB}"
    echo "JOBID   = ${JOBID}"
fi

if [[ ! -z "${SLURM_JOB_ID}" ]]; then
    echo "----- waiting for ${SLURM_JOB_ID} to be killed -----"
    sleep_time=${SLURM_SLEEP:-600}
    sleep "${sleep_time}"
fi
