#!/bin/sh

# SCRIPT NAME:  err_check
#
# ABSTRACT:  This script checks a return code in $err.  If $err=0
# a message that the program completed is put in the job outputfile and
# in a log file.  If $err != 0 then fail messages are put in job
# output file and the job is terminated.
#
# USAGE:  To use this script one must export the following variables
# to the script:  err, pgm, pgmout, jobid

err=${err:-""}           # Return code from program
pgm=${pgm:-""}           # Program name
COREROOT=${COREROOT:-""} # Directory to copy core files to
DATA=${DATA:-""}         # Working directory

if [ -z "${err}" ]; then
    err_exit "RETURN CODE NOT EXPORTED prior to running err_chk"
    exit
fi
if [ "${err}" -eq 0 ]; then
    echo "${pgm} completed cleanly"
    exit
fi

#  If error return code is 139, then program segfaulted.
#  Look for any core files, and save them to a directory in /ptmp
if [ "${err}" -eq 139 ]; then
    if [ -z "${COREROOT}" ]; then
        >&2 echo "SegFault reported but \$COREROOT variable not set. Will not copy files."
    else
        >&2 echo "SegFault reported. Copying core files to ${COREROOT}"
        if [ -z "${DATA}" ]; then
            >&2 echo "  \$DATA variable not set. Cannot copy core files!"
        else
            if ! cd "${DATA}"; then
                >&2 echo "  Cannot cd to DATA directory ${DATA}. Cannot copy core files!"
                err_exit $@
            fi
            if [ -s core ]; then
                mkdir -p "${COREROOT}"
                cp -p core "${COREROOT}/${pgm}.$$.core"
            else
                core_list=$(find . -maxdepth 1 -type f -name "core.*")
                for core_file in ${core_list}; do
                    if [ -s "${core_file}" ]; then
                        mkdir -p "${COREROOT}"
                        cp -p "${core_file}" "${COREROOT}/"
                    fi
                done
            fi
            coredirs=$(find . -maxdepth 1 -type d -name "coredir.*")
            for coredir in ${coredirs}; do
                mkdir -p "${COREROOT}/${coredir}"
                cp -p "${coredir}"/* "${COREROOT}/${coredir}/"
            done
        fi
    fi
fi
err_exit $@
