# This is a GitHub actions workflow for the NCEPLIBS-prod_util project.
#
# This workflow builds as the developer would, with develop branch of
# bacio and w3emc, with documentation build and code coverage.
#
# Ed Hartnett 10/9/23
name: developer
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  developer:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install faketime doxygen gcovr

    - name: checkout-bacio
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build && cd build
        cmake -DCMAKE_INSTALL_PREFIX=~/bacio ..
        make -j2
        make install

    - name: checkout-w3emc
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: develop

    - name: build-w3emc
      if: steps.cache-w3emc.outputs.cache-hit != 'true'
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake -DBUILD_WITH_BUFR=OFF -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc ..
        make -j2
        make install

    - name: checkout-prod_util
      uses: actions/checkout@v4
      with:
        path: prod_util

    - name: build-prod_util
      run: |
        cd prod_util
        mkdir build && cd build
        cmake -DCMAKE_PREFIX_PATH="~/bacio;~/w3emc" -DCMAKE_Fortran_FLAGS="-g -fprofile-abs-path -fprofile-arcs -ftest-coverage -O0 -Wall -fno-omit-frame-pointer -fsanitize=address" -DCMAKE_C_FLAGS="-g -fprofile-abs-path -fprofile-arcs -ftest-coverage -O0 -Wall -fno-omit-frame-pointer -fsanitize=address" ..
        make -j2
        ctest --output-on-failure --verbose
        gcovr --root .. -v  --html-details --exclude ../tests --exclude CMakeFiles --print-summary -o test-coverage.html &> /dev/null
        make install

    - name: upload-test-coverage
      uses: actions/upload-artifact@v3
      with:
        name: prod_util-test-coverage
        path: |
          prod_util/build/*.html
          prod_util/build/*.css

        
