# This is a GitHub actions workflow for the NCEPLIBS-prod_util project.
#
# This workflow builds with GCC
#
# Alex Richert, Sep 2023, Ed Hartnett
name: Linux_versions
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc
    strategy:
      fail-fast: true
      matrix:
        w3nco-version: [2.4.1]

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install faketime

    - name: cache-w3nco
      id: cache-w3nco
      uses: actions/cache@v3
      with:
        path: ~/w3nco
        key: w3nco-GCC-${{ runner.os }}-${{ matrix.w3nco-version }}

    - name: checkout-w3nco
      if: steps.cache-w3nco.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-w3nco
        path: w3nco
        ref: v${{ matrix.w3nco-version }}

    - name: build-w3nco
      if: steps.cache-w3nco.outputs.cache-hit != 'true'
      run: |
        cd w3nco
        mkdir build
        cd build
        cmake -DBUILD_WITH_BUFR=OFF  -DCMAKE_INSTALL_PREFIX=~/w3nco ..
        make -j2
        make install

    - name: checkout-prod_util
      uses: actions/checkout@v4
      with:
        path: prod_util

    - name: build-prod_util
      run: |
        cd prod_util
        mkdir build && cd build
        CC=gcc-11 FC=gfortran-11 cmake .. -DCMAKE_PREFIX_PATH="~/w3nco"
        make -j2
        ctest --output-on-failure --verbose
