# This is a GitHub actions workflow for the NCEPLIBS-prod_util project.
#
# This workflow builds with GCC
#
# Alex Richert, Sep 2023, Ed Hartnett
name: Linux_versions
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux_versions:
    runs-on: ubuntu-latest
    env:
      FC: gfortran
      CC: gcc
    strategy:
      fail-fast: true
      matrix:
        bacio-version: [2.4.1, 2.5.0, 2.6.0]
        w3emc-version: [2.9.3, 2.10.0, 2.11.0]

    steps:

    - name: install-dependencies
      run: |
        sudo apt-get update
        sudo apt-get install faketime

    - name: cache-bacio
      id: cache-bacio
      uses: actions/cache@v3
      with:
        path: ~/bacio
        key: bacio-GCC-${{ runner.os }}-${{ matrix.bacio-version }}

    - name: checkout-bacio
      if: steps.cache-bacio.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: v${{ matrix.bacio-version }}

    - name: build-bacio
      if: steps.cache-bacio.outputs.cache-hit != 'true'
      run: |
        cd bacio
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install

    - name: cache-w3emc
      id: cache-w3emc
      uses: actions/cache@v3
      with:
        path: ~/w3emc
        key: w3emc-GCC-${{ runner.os }}-${{ matrix.w3emc-version }}-${{ matrix.bacio-version }}

    - name: checkout-w3emc
      if: steps.cache-w3emc.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: v${{ matrix.w3emc-version }}

    - name: build-w3emc
      if: steps.cache-w3emc.outputs.cache-hit != 'true'
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake -DBUILD_WITH_BUFR=OFF -DCMAKE_PREFIX_PATH=~/bacio -DCMAKE_INSTALL_PREFIX=~/w3emc ..
        make -j2
        make install

    - name: checkout-prod_util
      uses: actions/checkout@v4
      with:
        path: prod_util

    - name: build-prod_util
      run: |
        cd prod_util
        mkdir build && cd build
        CC=gcc-11 FC=gfortran-11 cmake .. -DCMAKE_PREFIX_PATH="~/bacio;~/w3emc"
        make -j2
        ctest --output-on-failure --verbose
